In [168]:
import numpy as np
import operator

In [169]:
supply = np.array([150,160,90])
demand = np.array([140,120,90,50])
costs = np.array([[16,18,21,12],[17,19,14,13],[32,11,15,10]])

n,m = costs.shape

In [170]:
supply

array([150, 160,  90])

In [171]:
demand

array([140, 120,  90,  50])

In [172]:
costs

array([[16, 18, 21, 12],
       [17, 19, 14, 13],
       [32, 11, 15, 10]])

In [173]:
X = np.full((n, m), np.nan)
allow_fill_X = np.ones((n, m), dtype=bool)
indices = [(i, j) for i in range(n) for j in range(m)]

In [174]:
X

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [175]:
allow_fill_X

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [176]:
indices

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3)]

In [177]:
C = np.copy(costs)

xs = sorted(zip(indices, C.flatten()), key=operator.itemgetter(1))

In [178]:
print(xs)

[((2, 3), 10), ((2, 1), 11), ((0, 3), 12), ((1, 3), 13), ((1, 2), 14), ((2, 2), 15), ((0, 0), 16), ((1, 0), 17), ((0, 1), 18), ((1, 1), 19), ((0, 2), 21), ((2, 0), 32)]


In [179]:
def _fill_zero_indice(i, j): 
    allow_fill_X[i, j] = False
    allowed_indices_i = [(i, jj) for jj in range(m) if allow_fill_X[i, jj]]
    allowed_indices_j = [(ii, j) for ii in range(n) if allow_fill_X[ii, j]]
    allowed_indices = allowed_indices_i + allowed_indices_j
    if allowed_indices:
        return allowed_indices[0]
    else:
        return None

In [180]:
s = np.copy(supply)
d = np.copy(demand)

for (i, j), _ in xs:
    get_min = min(s[i],d[j])
    print((i,j),get_min)
    if get_min == 0:
        continue
    elif not np.isnan(X[i,j]):
        continue
    else:
        X[i, j] = get_min
        if s[i] == get_min and d[j] == get_min:
            fill_zero_indices = _fill_zero_indice(i, j)
            if fill_zero_indices:
                X[fill_zero_indices] = 0
                allow_fill_X[fill_zero_indices] = False
        s[i] -= get_min
        d[j] -= get_min
        print(allow_fill_X)
    
    if d[j] == 0:
        allow_fill_X[:,j] = False
    if s[i] == 0:
        allow_fill_X[i,:] = False

(2, 3) 50
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
(2, 1) 40
[[ True  True  True False]
 [ True  True  True False]
 [ True  True  True False]]
(0, 3) 0
(1, 3) 0
(1, 2) 90
[[ True  True  True False]
 [ True  True  True False]
 [False False False False]]
(2, 2) 0
(0, 0) 140
[[ True  True False False]
 [ True  True False False]
 [False False False False]]
(1, 0) 0
(0, 1) 10
[[False  True False False]
 [False  True False False]
 [False False False False]]
(1, 1) 70
[[False False False False]
 [False False False False]
 [False False False False]]
(0, 2) 0
(2, 0) 0


In [181]:
for idx in range(3):
    print(costs[idx,:],supply[idx])

print(demand)
print(X)

[16 18 21 12] 150
[17 19 14 13] 160
[32 11 15 10] 90
[140 120  90  50]
[[140.  10.  nan  nan]
 [ nan  70.  90.  nan]
 [ nan  40.  nan  50.]]


In [182]:
X_final = np.copy(X)
for i in range(0, n):
    for j in range(0,m):
        if np.isnan(X_final[i, j]):
            X_final[i, j] = 0
            
sumT = np.sum(X_final*C)
print(sumT)

5950.0
